export default class Item{
    itemList={
        autoClicker:{
            price:2000,
            level:0,
            dmg:0.3,
        },
        spiritStoneUpgrade:{
            price:500,
            level:0,
            multiplier:1,
        },
        flyingSword:{
            price:200000,
            owned:false,
            multiplier:2,
        },
        berserkPill:{
            price:20000,
            active:false,
            multiplier:2,
            duration:300000
        },
        frenzyPotion:{
            price:20000,
            active:false,
            multiplier:2,
            duration:300000
        },
        mortalScroll:{
            price:1000,
            owned:false,
            multiplier:2,
        },
        earthScroll:{
            price:10000,
            owned:false,
            multiplier:3,
        },
        havenScroll:{
            price:100000,
            owned:false,
            multiplier:5,
        },
        divineScroll:{
            price:1000000,
            owned:false,
            multiplier:10,
        },

    };
    

}
